# Generated by Django 5.0.1 on 2024-01-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sivi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='connections',
            field=models.ManyToManyField(blank=True, to='sivi_app.user'),
        ),
    ]
