# Generated by Django 5.0.1 on 2024-01-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sivi_app', '0002_user_connections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='connections',
        ),
        migrations.AddField(
            model_name='user',
            name='connections',
            field=models.JSONField(default=list),
        ),
    ]
