# Generated by Django 5.0.1 on 2024-01-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sivi_app', '0003_remove_user_connections_user_connections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='connections',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
