# Generated by Django 5.0.1 on 2024-01-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sivi_app', '0004_alter_user_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='socket_code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
